/**
 * Real Koshish 2026 competition sub-events, with rules paraphrased/summarized
 * from the official KOSHISH_2026_RULE_BOOK.docx supplied by PCTE.
 * Points system per the rule book: Group events 15/10/6, Solo & other
 * individual events 10/6/3, plus a flat +1 participation / -1 non-participation
 * mark applied at the class level (noted in generalRule, not per-event points).
 */

const GROUP_POINTS = { first: 15, second: 10, third: 6, participation: 1 };
const SOLO_POINTS = { first: 10, second: 6, third: 3, participation: 1 };

const koshishCompetitionEvents = [
  {
    name: 'Debate (British Parliamentary)',
    slug: 'debate',
    category: 'literary',
    format: 'team',
    teamSize: { min: 3, max: 3 },
    pointsSystem: GROUP_POINTS,
    timeAllowed: '3-5 minutes per speaker (varies by round)',
    hasPreliminaryRound: true,
    orderIndex: 1,
    rules: [
      'Format: British Parliamentary — two teams per round, Government vs Opposition, three speakers per team.',
      "Government defines the motion, builds a positive case, and responds to Opposition challenges.",
      "Opposition responds to the Government's definition and constructs a case against the motion.",
      'Each speaker (Leader, Deputy Leader, Member, Whip) has a distinct role; Whips may not introduce new arguments.',
      'Points of Order such as slang, defamatory language, aggressive behaviour, or unparliamentary terms are unacceptable.',
      'Strict formal dress code applies; failing to abide by it leads to negative consequences for the team.',
      'Full rule book explained in an orientation session by the concerned event in-charges (Annexure-1).',
    ],
    judgingCriteria: ['Argument quality', 'Rebuttal & engagement', 'Role fulfilment', 'Parliamentary conduct'],
  },
  {
    name: 'Nukkad Natak',
    slug: 'nukkad-natak',
    category: 'group',
    format: 'team',
    teamSize: { min: 6, max: 10 },
    pointsSystem: GROUP_POINTS,
    timeAllowed: '5-7 minutes',
    orderIndex: 2,
    rules: [
      '6 to 10 participants per team.',
      'Time allowed: 5-7 minutes.',
      'Own theme — teams choose their own subject for the street play.',
      'Note: a class team may participate in only TWO out of the four cultural events (Nukkad Natak, Fashion Show, International Group Dance, Indian Group Dance).',
    ],
  },
  {
    name: 'Fashion Show',
    slug: 'fashion-show',
    category: 'group',
    format: 'team',
    teamSize: { min: 6, max: 10 },
    pointsSystem: GROUP_POINTS,
    timeAllowed: '3-4 minutes',
    orderIndex: 3,
    rules: [
      'Own theme; team of 6-10 members.',
      'Background tracks must be submitted on pen drive/CD well before the event begins.',
      'Time allowed: 3-4 minutes. Props are allowed.',
      'Judging follows a fixed sequence: Walk, Choreography/Music, Clothing, Expressions according to theme.',
      'Note: a class team may participate in only TWO out of the four cultural events.',
    ],
    judgingCriteria: ['Walk', 'Choreography/Music', 'Clothing', 'Expressions according to theme'],
  },
  {
    name: 'International Group Dance',
    slug: 'international-group-dance',
    category: 'group',
    format: 'team',
    teamSize: { min: 6, max: 10 },
    pointsSystem: GROUP_POINTS,
    timeAllowed: '4-6 minutes',
    orderIndex: 4,
    rules: [
      '6 to 10 participants.',
      'Time allowed: 4-6 minutes.',
      'Songs or instrumental music must strictly be International.',
      'Props are allowed.',
      'Note: a class team may participate in only TWO out of the four cultural events.',
    ],
  },
  {
    name: 'Indian Group Dance',
    slug: 'indian-group-dance',
    category: 'group',
    format: 'team',
    teamSize: { min: 6, max: 10 },
    pointsSystem: GROUP_POINTS,
    timeAllowed: 'Max 3-5 minutes',
    orderIndex: 5,
    rules: [
      '6 to 10 participants.',
      'Time allowed: max 3-5 minutes.',
      'Recorded or live music is allowed.',
      'Any number of accompanists is allowed to perform.',
      'Note: a class team may participate in only TWO out of the four cultural events.',
    ],
  },
  {
    name: 'Ctrl+Play Esports (BGMI)',
    slug: 'ctrl-play-esports',
    category: 'esports',
    format: 'team',
    teamSize: { min: 4, max: 4 },
    pointsSystem: GROUP_POINTS,
    timeAllowed: 'Per scheduled match',
    orderIndex: 6,
    rules: [
      'Each class fields exactly ONE official team of 4 registered players (the class name is the official alias).',
      'Scoring: Total Score = Placement Points + Finish Points (1 point per confirmed elimination). Finals combine both match scores.',
      'Ties for the final qualifying position are resolved by a Team Deathmatch (TDM); the TDM decision is final.',
      'Teams must report 30 minutes before their scheduled match — late arrival means immediate disqualification, no grace period.',
      "Only smartphones are permitted — no tablets, emulators, controllers, or unauthorized peripherals; only BGMI's built-in voice chat is allowed.",
      'Matches are not restarted for internet failure, crashes, battery drain, or other individual technical issues — no exceptions.',
      'Cheating, hacking, scripts, macros, teaming or account sharing result in immediate disqualification.',
      'Full rules in Annexure-2, explained during the orientation session.',
    ],
  },
  {
    name: 'PCTE Mr. & Miss Punjab',
    slug: 'mr-and-miss-punjab',
    category: 'other',
    format: 'individual',
    teamSize: { min: 1, max: 1 },
    pointsSystem: { first: 10, second: 6, third: 3, participation: 1 },
    timeAllowed: 'Rounds floated by faculty in-charge',
    orderIndex: 7,
    rules: [
      'Compulsory for every class to send at least one participant in each category (Mr. and Miss).',
      'Classes compete on total participation brought (from within the class plus outside participants), scored 10/6/3 for first/second/third.',
      'Participation amount must be submitted at the accounts office under the class name.',
      'If a PCTE student wins a position, the winning points are also credited to their class for the Koshish Trophy.',
      'Detailed rules and rounds floated separately by the concerned faculty in-charges.',
    ],
  },
  {
    name: 'Solo Dance',
    slug: 'solo-dance',
    category: 'solo',
    format: 'individual',
    teamSize: { min: 1, max: 1 },
    pointsSystem: SOLO_POINTS,
    timeAllowed: '3-5 minutes',
    hasPreliminaryRound: true,
    orderIndex: 8,
    rules: [
      'Only one participant allowed per class.',
      'Preliminary round followed by the final.',
      'Time allowed: 3-5 minutes.',
      'Own live or recorded music.',
    ],
  },
  {
    name: 'Western Solo Song',
    slug: 'western-solo-song',
    category: 'solo',
    format: 'individual',
    teamSize: { min: 1, max: 1 },
    pointsSystem: SOLO_POINTS,
    timeAllowed: '3-5 minutes',
    hasPreliminaryRound: true,
    orderIndex: 9,
    rules: [
      'Only one participant allowed per class.',
      'Preliminary round followed by the final.',
      'Time allowed: 3-5 minutes.',
      'Only English songs are considered Western.',
      'Two professional accompanists are allowed; recorded music is allowed.',
    ],
  },
  {
    name: 'Indian Solo Song',
    slug: 'indian-solo-song',
    category: 'solo',
    format: 'individual',
    teamSize: { min: 1, max: 1 },
    pointsSystem: SOLO_POINTS,
    timeAllowed: '3-5 minutes',
    hasPreliminaryRound: true,
    orderIndex: 10,
    rules: [
      'Only one participant allowed per class.',
      'Preliminary round followed by the final.',
      'Time allowed: 3-5 minutes.',
      'Two professional accompanists are allowed; recorded music is allowed.',
    ],
  },
  {
    name: 'Mono Acting',
    slug: 'mono-acting',
    category: 'dramatics',
    format: 'individual',
    teamSize: { min: 1, max: 1 },
    pointsSystem: SOLO_POINTS,
    timeAllowed: '3-5 minutes',
    hasPreliminaryRound: true,
    orderIndex: 11,
    rules: [
      'Only one participant allowed per class.',
      'Content must not be religiously sentimental.',
      'Preliminary round before the final.',
      'Duration: 3 to 5 minutes.',
      'Any vulgarity leads to disqualification.',
    ],
  },
  {
    name: 'Dumb Charades',
    slug: 'dumb-charades',
    category: 'literary',
    format: 'team',
    teamSize: { min: 2, max: 2 },
    pointsSystem: SOLO_POINTS,
    timeAllowed: '1 minute per slip',
    orderIndex: 12,
    rules: [
      "One team's participation is compulsory per class; a second team is optional (max 1 participation mark per class).",
      'Each team has 2 participants — one acts, one guesses. Time allowed: 1 minute.',
      'No lip movement or speaking is allowed while acting.',
      'The full/proper name must be guessed; incomplete names do not count.',
      'Gestures can be used but cannot be broken into individual letters.',
      'A 30-second penalty applies if there is no correct guess in time.',
    ],
  },
  {
    name: 'Picto',
    slug: 'picto',
    category: 'literary',
    format: 'team',
    teamSize: { min: 2, max: 2 },
    pointsSystem: SOLO_POINTS,
    timeAllowed: '60 seconds per slip',
    orderIndex: 13,
    rules: [
      "One team's participation is compulsory per class; a second team is optional (max 1 participation mark per class).",
      'Team of 2 — one describes the object on a slip, the other draws it. Time allowed: 60 seconds.',
      'Participants may not see each other during play.',
      'Explanation is limited to geometric figures — lines, squares, triangles, circles, hexagons.',
      'The guesser may make unlimited guesses; the describer may only respond "YES", "NO", or "OF-SORTS".',
      'A 30-second penalty applies if there is no guess within the time limit.',
    ],
  },
  {
    name: 'Quiz',
    slug: 'quiz',
    category: 'literary',
    format: 'team',
    teamSize: { min: 2, max: 2 },
    pointsSystem: SOLO_POINTS,
    timeAllowed: 'Written prelims + oral final',
    hasPreliminaryRound: true,
    orderIndex: 14,
    rules: [
      'Three teams per class may enter; each class gets a maximum of 1 participation mark.',
      'Each team consists of 2 participants and sits a written preliminary test.',
      'The best 6 teams advance to the final.',
      'The final round is oral, spanning History, Current Affairs, Business, Personalities, Science & Technology, and Geography (Indian and international).',
    ],
  },
  {
    name: 'Extempore',
    slug: 'extempore',
    category: 'literary',
    format: 'individual',
    teamSize: { min: 1, max: 1 },
    pointsSystem: SOLO_POINTS,
    timeAllowed: '3-4 minutes (after 4 min prep)',
    orderIndex: 15,
    rules: [
      'Only one participant allowed per class; max 1 participation mark per class.',
      'Language: English.',
      'Each participant is given a topic by slip and 4 minutes to prepare.',
      'Speaking time: 3-4 minutes. A bell rings after three minutes and again after four.',
    ],
  },
  {
    name: 'JAM (Just A Minute)',
    slug: 'jam',
    category: 'literary',
    format: 'individual',
    teamSize: { min: 1, max: 1 },
    pointsSystem: SOLO_POINTS,
    timeAllowed: '60 seconds',
    orderIndex: 16,
    rules: [
      'Only one participant allowed per class; max 1 participation mark per class.',
      'A topic is given on the spot to contestants in a group. Language: English.',
      'Contestants must speak continuously for 60 seconds without pause or repeating a word or idea more than twice.',
      'Speaking continuously for 5 seconds earns a point; a correctly upheld objection also earns a point, an invalid one costs a point.',
      'Finishing the topic within time earns an extra point.',
    ],
  },
  {
    name: 'Business Plan',
    slug: 'business-plan',
    category: 'literary',
    format: 'team',
    teamSize: { min: 2, max: 2 },
    pointsSystem: SOLO_POINTS,
    timeAllowed: '2-min elevator pitch (prelims), 8-10 min final pitch',
    hasPreliminaryRound: true,
    orderIndex: 17,
    rules: [
      'One team per section is mandatory (2 students); a second team is optional. Treated as an individual event for scoring.',
      'Prelims: a 10-12 slide PDF plus a strict 2-minute elevator pitch — the pitch is cut off when the bell rings.',
      'PDF must cover Problem/Solution, USP, supporting data, competitor analysis, milestones/traction, statutory registrations, social handles and team.',
      'Ideas previously presented at Koshish/other startup competitions or that already received funding are not eligible.',
      '8 shortlisted ideas per wing (Junior & Senior) pitch live to an Angel Investor with a 12-14 slide deck, strictly 8-10 minutes plus Q&A.',
      'Evaluated on objective/problem-solving, team, market landscape, scalability, customers/suppliers, competitive analysis, sales & marketing, and financial assessment.',
    ],
  },
  {
    name: 'Group Discussion',
    slug: 'group-discussion',
    category: 'literary',
    format: 'team',
    teamSize: { min: 1, max: 10 },
    pointsSystem: SOLO_POINTS,
    timeAllowed: '2 min think + 10-12 min discussion',
    orderIndex: 18,
    rules: [
      'Maximum 10 students per class is mandatory.',
      'Topics are given on the spot; language is English.',
      '2 minutes to think, followed by a 10-12 minute group discussion.',
    ],
  },
  {
    name: 'Fixathon',
    slug: 'fixathon',
    category: 'creative_fine_art',
    format: 'team',
    teamSize: { min: 2, max: 2 },
    pointsSystem: GROUP_POINTS,
    timeAllowed: '5-min demo + 2-min Q&A (final round)',
    hasPreliminaryRound: true,
    orderIndex: 19,
    rules: [
      'Design event — teams of 2 design one original product solving a real-life problem (daily life, utility, or community need).',
      'Must present a working prototype: physical, software/digital, or offline working model.',
      'Copied designs, plagiarized concepts, or unsafe/illegal/unethical products will be disqualified; originality may be AI-verified.',
      'Must clearly show the flow: Problem → User → Product → Utility.',
      'Round 1: idea & problem identification. Round 2: product design & development with a prototype. Round 3: 5-minute demo/pitch + 2-minute Q&A.',
      'Full rules in Annexure-3, explained during the orientation session.',
    ],
    judgingCriteria: ['Problem relevance', 'Originality', 'Working prototype', 'Presentation & Q&A'],
  },
  {
    name: 'Photography',
    slug: 'photography',
    category: 'creative_fine_art',
    format: 'individual',
    teamSize: { min: 1, max: 1 },
    pointsSystem: SOLO_POINTS,
    timeAllowed: 'Rolling daily submissions + final 10-image set',
    orderIndex: 20,
    rules: [
      'Each class must email 4 images daily by the announced deadline; missed submissions are disqualified.',
      'Image size must not exceed 5MB. Drones are not allowed.',
      'Final submission: a pen drive with the 10 best captioned images, labelled with Class-Section-Participant name.',
      'Images must be captioned appropriately — captions carry weight in judging. Only JPEG or PNG accepted, no RAW.',
      'Minimal editing only; no borders, frames or cropping. All images must be shot on the PCTE campus.',
      "Judges' decision is final.",
    ],
  },
  {
    name: 'Videography',
    slug: 'videography',
    category: 'creative_fine_art',
    format: 'individual',
    teamSize: { min: 1, max: 4 },
    pointsSystem: SOLO_POINTS,
    timeAllowed: '1-4 minutes',
    orderIndex: 21,
    rules: [
      'Duration: 1-4 minutes, shot only on the PCTE campus. Drones are not allowed.',
      'Theme must be "Koshish" — plot, documentary or docudrama style; no still-shot sequences and it cannot be an advertisement.',
      'Only royalty-free music; mixing and editing must be done by students only.',
      'Uploaded to the PCTE YouTube channel by the announced deadline — 25% of the score is based on YouTube likes, 75% on storyline, cinematography, editing and acting.',
      "Judges' decision is final.",
    ],
  },
  {
    name: 'Canvas Painting',
    slug: 'canvas-painting',
    category: 'creative_fine_art',
    format: 'individual',
    teamSize: { min: 1, max: 1 },
    pointsSystem: SOLO_POINTS,
    timeAllowed: 'Multi-day, communicated schedule',
    orderIndex: 22,
    rules: [
      'A 24" x 36" canvas is provided by the college to every team.',
      'One student per class paints, on-campus only, supervised by the class teacher-in-charge.',
      'Own theme.',
      'Campus-I and Campus-II classes submit their canvas at their respective campus library at the end of each painting day.',
    ],
  },
];

module.exports = koshishCompetitionEvents;
